### ISSUE TITLE
SEARCH: drop the search API

### ISSUE THREAD

**Issue by jacoscaz** [beautifulinteractions/node-quadstore#104]
Assuming we choose to follow through with #103, the SEARCH API would become a redundant, less-powerful alternative to the SPARQL API. It wouldn't make sense to keep it around.

**Comment by gsvarovsky** [comment]
Actually the search API might be very useful to me.

The reason is, my project has a [json-rql](https://json-rql.org/) interface. It looks like it would be better for me to use your search API directly, rather than translating first to SPARQL.

I will try to investigate as soon as possible. When do you anticipate doing this work?

**Comment by jacoscaz** [comment]
@gsvarovsky interesting! I'm still brainstorming on this and I am really happy to get some community feedback.

Consider that the work on the SPARQL API will bring support for SPARQL queries expressed both as SPARQL strings _and_ as SPARQL Algebra objects (see https://www.npmjs.com/package/sparqlalgebrajs). From the looks of it, converting a JSON RQL query to a SPARQL Algebra object should not be any more difficult than converting the same query to use with quadstore's Search API. 

What do you think? I would otherwise be happy to figure out how to keep the search API around.

**Comment by gsvarovsky** [comment]
You are right, using the algebra will be just as good as the current search API, probably even better. Thanks!

**Comment by jacoscaz** [comment]
No worries! Thank _you_ for mentioning JSON RQL, I wasn't aware of it. I will come back to this issue in a while, once work on SPARQL continues.

**Comment by jacoscaz** [comment]
Release on NPM - `quadstore@7.0.1-alpha.9`
