### ISSUE TITLE
SPARQL: replace current implementation with a custom Comunica engine + the upcoming RDF/JS spec

### ISSUE THREAD

**Issue by jacoscaz** [beautifulinteractions/node-quadstore#105]
Things have changed over the course of the last few months:

- `comunica` has added support for SPARQL `UPDATE` queries;
- work on adding a new interface to RDF/JS that would allow `comunica` to push filters down to `quadstore` is ongoing;
- @rubensworks is doing a wonderful job in documenting how to create custom `comunica` engines, making it easier and easier to produce bundles of reasonable size.

Whereas there's still something to be said for a completely custom SPARQL engine, we could easily adapt what we have so far to support the new RDF/JS interface and move forward with a `comunica`-based SPARQL engine. That would give us something incredibly more powerful than what we could accomplish ourselves. Also, given the team who's working on `comunica`, I don't think we would incur in any performance issues.

**Comment by rubensworks** [comment]
> comunica has added support for SPARQL UPDATE queries;

We actually don't have update support yet but it's a WIP though!
So this will probably a blocker for you until we get that done.


Happy to help with creating custom configs if needed.

**Comment by jacoscaz** [comment]
That's not a big issue - we could handle `UPDATE` queries internally while delegating `SELECT` and others to Comunica. It seems like the `query()` method can accept both SPARQL queries in string form and instances of `sparqlalgebrajs'` `Operation` (https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/lib/ActorInitSparql-browser.ts#L133), so it should be relatively easy to start by using our own internal handling of SPARQL queries for `UPDATE` queries and move to Comunica's when ready (and contribute to Comunica in the meantime!)

**Comment by rubensworks** [comment]
> we could handle UPDATE queries internally while delegating SELECT and others to Comunica.

That's sounds like a good option for now indeed.

> It seems like the query() method can accept both SPARQL queries in string form and instances of sparqlalgebrajs' Operation

Indeed!

**Comment by jacoscaz** [comment]
This is coming along nicely in #107 through https://github.com/beautifulinteractions/node-quadstore-comunica

**Comment by jacoscaz** [comment]
Release on NPM - `quadstore@7.0.1-alpha.9`
