### ISSUE TITLE
Dev dependency required to actor-init-sparql

### ISSUE THREAD

**Issue by gsvarovsky** [beautifulinteractions/node-quadstore#116]
Working in Typescript, I had to add a `devDependency` to `@comunica/actor-init-sparql` so that the typings for Comunica are available and the project compiles.

This is a dev dependency only because `node-quadstore-comunica` bundles the Comunica code.

**Comment by jacoscaz** [comment]
I think the best way to address this is to include the relevant typings within `quadstore-comunica` by either copying them or crafting them by hand.

Any other solution I was able to come up with would result in having the entire `comunica` framework as a dependency of `quadstore`, much as you're experiencing right now, and I feel that would not be a healthy direction.

**Comment by jacoscaz** [comment]
@gsvarovsky could you test this with `quadstore@7.1.0-beta.0`, which I've just released to NPM with the `beta` tag?

**Comment by gsvarovsky** [comment]
Fixed in quadstore@7.1.0-beta.1
