### ISSUE TITLE
String literal data type is not compacted

### ISSUE THREAD

**Issue by gsvarovsky** [beautifulinteractions/node-quadstore#118]
https://github.com/beautifulinteractions/node-quadstore/blob/faf3cd5f694b329d0d486f07bbdd4dd835de7030/lib/serialization/import.ts#L19

The `xsd.string` data type is not subjected to compaction when using `prefixes`.

If it were compacted, it would still be subject to expansion in the current export module: https://github.com/beautifulinteractions/node-quadstore/blob/faf3cd5f694b329d0d486f07bbdd4dd835de7030/lib/serialization/export.ts#L14

**Comment by jacoscaz** [comment]
Ah, good catch. Will fix soon!

**Comment by jacoscaz** [comment]
Fixed this in https://github.com/beautifulinteractions/node-quadstore/commit/1400bbe15bb88976d6a8cc262bb8f7503e9ed5d2, will release in either `7.1.0` or the next beta. Let me know if this is urgent for you and I'll release another beta right away.
