### ISSUE TITLE
COMUNICA: support custom comunica configurations

### ISSUE THREAD

**Issue by jacoscaz** [beautifulinteractions/node-quadstore#122]
As of v7.1.0, `quadstore` does not support any Comunica configuration other than [`quadstore-comunica`](https://github.com/beautifulinteractions/node-quadstore-comunica), which optimizes for bundle size and dependency count to deliver the smallest possible Comunica configuration that still manages to evaluate queries.

`comunica-quadstore` does not include anything else but the subset of actors that are required to get from a SPARQL non-federated query to its RDF/JS results, leaving out parsers, serializers, federation, GraphQL and a bunch of other features supported by Comunica.

We should probably allow developers to pass custom engine factory functions to `quadstore`'s constructor.

**Comment by jacoscaz** [comment]
Released with `quadstore@8.0.0-alpha.3` (watch out for the new **required** constructor option!).

**Comment by markmelville** [comment]
I'm experimenting with quadstore as a server that fronts a small amount of data, in a distributed linked data network. As such, I'd like to be able to execute federated queries.

This issue and its resolution seem to indicate that, although quadstore-comunica has chosen not to implement it, I should be able to provide a custom function. I can't find any examples, docs, or code that is helping me to see how to do this. Can anyone provide some pointers? Thanks in advance.
