### ISSUE TITLE
sparql() result format does not match Query Results JSON Format

### ISSUE THREAD

**Issue by antoine-morvan** [beautifulinteractions/node-quadstore#133]
Hello, 

I'm in the process of updating from the old repo (quastdore 6.0.0 + quadstore-sparql) and I'm wondering why the sparql() method does not return a JSON matching the Query Results JSON Format (https://www.w3.org/TR/sparql11-results-json/) ?

Also, in the doc I did not see any mention to a helper function that would build it up. Did I miss it ?

**Comment by jacoscaz** [comment]
Hello @antoine-morvan !

With the advent of the RDF/JS spec and ecosystem of libraries we've opted to reduce quadstore's surface area and let developers complement it with other libraries, according to the specific needs of each project.

This was done mainly for two reasons:

1) address the ballooning size of browser-side bundles, which was making usage of quadstore impractical in client-side contexts;
2) clear positioning of quadstore within the RDF/JS ecosystem and a narrower focus, allowing us to allocate more effort on quadstore's distinguishing features (that of being a persistent store) while benefitting (and contributing to!) other projects for requirements such as serialization, etc...

That said, there's a number of ways in which you can add serialization support to your project. One of them is to fork [quadstore's custom configuration of Comunica](https://github.com/beautifulinteractions/node-quadstore-comunica) and include the required serializer actors. This would be relatively easy to do and would allow you to pull in any new change from the original repository.

**Comment by antoine-morvan** [comment]
Thanks for the quick answer.

**Comment by jacoscaz** [comment]
No worries. I will close this for now but please feel free to follow up here on GitHub or get in touch with me directly (see package.json for my email).

**Comment by jacoscaz** [comment]
Ah, I forgot - if you can and feel comfortable doing so, we'd appreciate having a brief description of your use case in [this discussion thread](https://github.com/beautifulinteractions/node-quadstore/discussions/112). It would help us understand how others are using quadstore, which in turn allows us to better prioritize issues.
