### ISSUE TITLE
Advanced queries (searches)

### ISSUE THREAD

**Issue by jacoscaz** [beautifulinteractions/node-quadstore#3]
How to implement advanced queries? We need a few key components:

- query planner
- query optimizer
- query executor

The optimizer could go in a later release. 

How to implement joins? I've had a preliminary look and it looks like the "merge-sort join" algorithm would be a good pick as we're using lexicographically-ordered index keys.

**Comment by jacoscaz** [comment]
Potential strategy:

1) order queries based on approxResultSize() and variables (each query should have a variable in common with the next one)
2) execute first query, re-order results based on second query's vars as they stream in
3) execute next query. filter results from previous query as those from the query stream in, re-order results based on next query's vars
4) repeat 4 for each query

See http://www.collectionsjs.com/sorted-map

**Comment by elf-pavlik** [comment]
I think @RubenVerborgh could offer some feedback based on implementing [Linked Data Fragments](http://linkeddatafragments.org/) servers. I also remember talking with him and @bergos about using something similar to LevelGraph's navigator API (https://github.com/rdf-ext/clownface) as higher level interface for RDF Stores. From what I remember Triple Pattern Fragments require Stores to provide fast estimated counts. I also recall hearing about plans for Quad Pattern Fragments :)

**Comment by RubenVerborgh** [comment]
There's much more to say about this than can possibly fit in a comment here. Count are part of the input of the query planner indeed. We'll be working on a generic SPARQL engine the coming months/years, in which this could be plugged in, but I'm not sure whether the timeframes will match.

**Comment by jacoscaz** [comment]
Moved forward to v0.1.0 in place of better unit tests due to internal requirements.

**Comment by jacoscaz** [comment]
Closing this one. Bugs and new features shall go into dedicated issues.
