### ISSUE TITLE
Allow del with matchPattern

### ISSUE THREAD

**Issue by jmatsushita** [beautifulinteractions/node-quadstore#32]
Hi there,

I ran into something I found counter-intuitive. I was trying out `db.patch` and then switched to `db.del` and couldn't understand why the delete didn't occur until I realised (reading the doc) that `del` doesn't support the matchPattern syntax. It would be quite nice for consistency (and functionality) if `del` acted like the first argument of patch (array means actual deletes, and single object means matchPattern).

Also it might be useful to have a [delExisting method like in LD-PATCH](https://dvcs.w3.org/hg/ldpwg/raw-file/ldpatch/ldpatch.html#DeleteExisting-statement) and possibly a putNew (like addNew) method?

Finally, being able to use the query interface with filters and joins to delete would be nice. Maybe using the chaining syntax? Maybe using `.get()` instead of `toArray` would make a `.del()` fit nicely at the end of the chain? 

Cheers,

Jun

**Comment by jmatsushita** [comment]
Of course a quick workaround was to use `.patch(matchPattern, [], done)`

**Comment by jacoscaz** [comment]
@jmatsushita could you please create a different issue for each of these points? I think they're all very good and deserve to be tracked separately.

**Comment by jmatsushita** [comment]
There you go :)

**Comment by jacoscaz** [comment]
@jmatsushita this one should now work as expected. We'll release on NPM over the next few days.

**Comment by jmatsushita** [comment]
Great!

**Comment by jacoscaz** [comment]
We have now released this feature in version 2.1.1. Closing this one, bugs should go into dedicated issues.
