### ISSUE TITLE
Add delExisting and putNew

### ISSUE THREAD

**Issue by jmatsushita** [beautifulinteractions/node-quadstore#33]
From ##32
> Also it might be useful to have a delExisting method like in LD-PATCH and possibly a putNew (like addNew) method?

**Comment by jacoscaz** [comment]
To clarify:

- putNew acts like put but throws for quads already present in the store.
- delExisting acts like del but throws for quads that are not present in the store.

Another way to do this could be through a dedicated `opts` like `opts.throwIf(Not)Exist`.

**Comment by jmatsushita** [comment]
Yes that's what I meant. Dedicated `opts` would indeed work too!

**Comment by jacoscaz** [comment]
What about stream? Would this need to support streams (via `.on('error', (DuplicateQuadError err) => {})`)?

**Comment by jacoscaz** [comment]
@jmatsushita are you still interested in this feature?

**Comment by jacoscaz** [comment]
Cleaning up old issues, will reopen a new one if needed.
