### ISSUE TITLE
Chaining delete with query 

### ISSUE THREAD

**Issue by jmatsushita** [beautifulinteractions/node-quadstore#34]
From #32
> Finally, being able to use the query interface with filters and joins to delete would be nice. Maybe using the chaining syntax? Maybe using .get() instead of toArray would make a .del() fit nicely at the end of the chain?

**Comment by jacoscaz** [comment]
@jmatsushita which of the following would you like to see implemented?

1. `store.query().del()`
2. `store.remove(store.query())`?

I feel option n. 2 is cleaner and almost identical to the `.remove()`method from the `RdfStore` class, so I would be inclined to go with that.

**Comment by jmatsushita** [comment]
Ah yes, I was thinking 1 because it looks nicer but I can live with 2 especially if its close to the RDFJS API!

**Comment by jacoscaz** [comment]
@jmatsushita we've incorporated your suggestions within a bigger refactor of the whole API as we were not 100% happy about it and wanted to do a reach a more stable version of it before starting to use node-quadstore internally. You can now do either of the following:

1. `store.query().del((err) => {})`
2. `store.delStream(store.query().getStream(), (err) => {})`

Closing this one, bugs should go into dedicated issues.
