### ISSUE TITLE
Extending quadstore

### ISSUE THREAD

**Issue by jacoscaz** [beautifulinteractions/node-quadstore#40]
What if someone requires additional indexes for context-specific queries? How can `quadstore` support extensions? 

##### `registerIndex(String indexName, Function keyGenerator)`

- `indexName` - name of index to be created
- `keyGenerator` - function that generates an index key from a quad

##### `queryIndex(String indexName, Object opts)` and `queryIndexStream(String indexName, Object opts)`

- `indexName` - name of index to be queried
- `opts` - query options
    - `opts.start` - leveldb's `gte` minus `indexName`
    - `opts.end` - leveldb's `lte` minus `indexName`

### Other stuff

- make `store._delimiter` and `store._boundary` public

**Comment by jmatsushita** [comment]
Would registerIndex create a new index or use an existing one? It would be good to use an existing one to benefit from the leveldb ecosystem.

**Comment by jmatsushita** [comment]
Ah think I see, you do mean an existing one, but it needs to be registered to match keys during the joins? I think I need to think more about this and play with `search-index` to contribute better to the conversation :) The main use case I was thinking of was to reuse a search index with a quadstore instance.

**Comment by jacoscaz** [comment]
@jmatsushita have a look at https://github.com/jacoscaz/node-quadstore/blob/indexes/test/quadstore.js#L672 . It's a basic demonstration of the api I was thinking about. The test implements an index that would take care of #39 . What do you think?

**Comment by jacoscaz** [comment]
@jmatsushita ?

**Comment by jacoscaz** [comment]
See pull request #42

**Comment by jacoscaz** [comment]
Closing, available on NPM in quadstore@2.2.0-alpha .
