### ISSUE TITLE
JSON-LD support

### ISSUE THREAD

**Issue by Frando** [beautifulinteractions/node-quadstore#61]
Does node-quadstore support direct loading of JSON-LD (including context handling)? If not, is it a planned feature?
Same would be nice for output (so returning query results as JSON-LD).

Basically, does something like [levelgraph-jsonld](https://github.com/levelgraph/levelgraph-jsonld) exist for node-quadstore?

**Comment by akuckartz** [comment]
:+1:

**Comment by jacoscaz** [comment]
Hello @Frando. Thank you for checking out `quadstore`! At the moment we're not thinking of implementing direct JSON-LD loading as we'd like to stick to the [RDF/JS Interface Specification](https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md) and leave such a thing to dedicated modules.

I am unsure as to whether the `jsonld` module currently supports the RDF/JS Interface but we will need to use JSON-LD quite soon and will therefore necessarily look into this matter within the month. I haven't had the time to research this but my gut feeling would be that it'd be nice to have a transform stream to pipe `RdfStore.prototype.match()` streams into.

**Comment by elf-pavlik** [comment]
> I am unsure as to whether the jsonld module currently supports the RDF/JS Interface

* https://github.com/rdf-ext/rdf-parser-jsonld
* https://github.com/rdf-ext/rdf-serializer-jsonld-ext

**Comment by jacoscaz** [comment]
For reference:
- https://github.com/rdf-ext/rdf-parser-jsonld
- https://github.com/rdf-ext/rdf-serializer-jsonld

**Comment by Frando** [comment]
Hi, 
thanks all for the quick replies :-) This looks quite good actually, I will try things out.

**Comment by jacoscaz** [comment]
@Frando have you had any luck with this? Any feedback on `quadstore` itself or the overall process?

**Comment by Frando** [comment]
@jacoscaz not yet, this was for the time being more of an evaluation question. I'll report back once I get around to try things out actually.

**Comment by jacoscaz** [comment]
Closing this as it's been inactive for a while. @Frando I'll reopen if needed.
