### ISSUE TITLE
index-browser.js doesn't export RdfStore

### ISSUE THREAD

**Issue by elf-pavlik** [beautifulinteractions/node-quadstore#69]
I didn't make PR adding that export wanting to check first if you really need separate `browser` entry point and `quadstore.umd-bundle.js` in the repo.

Looking at https://github.com/beautifulinteractions/node-quadstore#browser I would find it sufficient to recommend `level-js` module, provide snippet from the `<script>` tag in that section and point people to webpack, rollup, browserify documentation for how they can build their application. Similar to:

https://github.com/rdfjs/N3.js#installation
> N3.js seamlessly works in browsers via [webpack](https://webpack.js.org/) or [browserify](http://browserify.org/). If you're unfamiliar with these tools, you can read [_webpack: Creating a Bundle – getting started_](https://webpack.js.org/guides/getting-started/#creating-a-bundle) or [_Introduction to browserify_](https://writingjavascript.org/posts/introduction-to-browserify).
You will need to create a "UMD bundle" and supply a name (e.g. with the `-s N3` option in browserify).

**Comment by elf-pavlik** [comment]
I haven't mentioned that webpack building for web will use `package.json` fields in order: `['browser', 'module', 'main']`
https://webpack.js.org/configuration/resolve/#resolvemainfields

Which means that it currently uses `index-browser.js` not `index.js`

**Comment by jacoscaz** [comment]
Hello @elf-pavlik . I somehow missed the notification for this feature. I will look at this over the next few days.

**Comment by jacoscaz** [comment]
@elf-pavlik just to make sure I understand what you are suggesting, you're saying I should:

- drop the pre-assembled UMD bundle
- remove the `browser` entry in `package.json`
- simply point people to `level-js` and bundlers such as `webpack` and `rollup` in the `README.md`

Is this correct? If so, why? I am not opposed to this, I just want to understand where you are coming from. Everything that simplifies things is more than welcome.

**Comment by elf-pavlik** [comment]
I think nowadays most developers know how to get npm modules working in web browser, sometimes it requires build tools and different people prefer different tools - webpack, rollup, browserify etc.

I recall N3.js used to provide automated browser build but then it just changed to that DIY approach. If you want to keep that UMD bundle I see no big problem with that, it would just require making sure that `index-browser.js` exports `RdfStore`.

**Comment by jacoscaz** [comment]
No, I think you are right in your assessment. Tools such as webpack and rollup have been around long enough that it doesn't make sense to ship pre-assembled bundles anymore. I'll address the points in my previous comment over the next few days.

By the way, I haven't had time to keep track of RDF/JS' evolution over the last few months. At a glance, is `quadstore` still up-to-date with the latest version of the spec? Are you currently using `quadstore` in some of your projects?

**Comment by elf-pavlik** [comment]
I use it in some experiments which require RDF/JS Source interface. For example to use this module
https://github.com/valueflows/vf-track-trace.ts I import RdfStore in https://github.com/valueflows/vf-cli.ts but I also started prototyping playground that should work in a browser and draw diagrams with D3.js

I think quadstore stays up to date with RDF/JS drafts and it stays listed on http://rdf.js.org/
One small feature we added to the spec `DataFactory#fromTerm` and `DataFactory#fromQuad` still haven't been added to `@rdfjs/data-model` but once it does you will just need to update that dependency.

BTW https://solidproject.org/ starts picking up so I also plan to use quadstore while prototyping some solid apps.

**Comment by jacoscaz** [comment]
@elf-pavlik does #71 solve your issue?

**Comment by elf-pavlik** [comment]
Looks good, thank you!

**Comment by jacoscaz** [comment]
Published to `npm` as `quadstore@6.0.1`!
