### ISSUE TITLE
Provide examples

### ISSUE THREAD

**Issue by ahka01** [beautifulinteractions/node-quadstore#70]
May provide a working example how to use the library to store triples inside it. It would be even better to include also queries using node-quadstore-sparql.

'This sample should parse a triples from a string variable or download a dataset from dbpedia for example. Then how we can query these data using the api of library or using sparql queries form quadstore-spraql.

Then would help a lot to have an overview on how to use the library.

Thanks in advance.

Regards,

**Comment by jacoscaz** [comment]
Hello @ahka01 . Apologies for the delay, I was on holiday. You are right, that's a good idea and a good thing to have in the README. I'll get around it over the next few days.

**Comment by ahka01** [comment]
Thanks a lot @jacoscaz. I am already excited about it.

**Comment by ahka01** [comment]
Helloe @jacoscaz,
it is a kindly reminder to provide an example how to use the library.
Thanks in advance.

**Comment by jacoscaz** [comment]
Hello @ahka01 . Again, apologies for the delay. I should be able to include a few examples on how to use this library in the next release.

**Comment by ahka01** [comment]
So the example I'm looking forward to have include two easy steps:

1. Read Triples(Quads) from ttl file or json-ld.
2. Query this file using sparql query

Thanks in advance

**Comment by jacoscaz** [comment]
This issue has been around for far too long without much activity. Quadstore's API has changed rather dramatically with version 7.0.1 (we're now at `7.0.1-alpha.9` on NPM), with tighter integration with other RDF/JS projects and the RDF/JS specs (with even more coming in the future). It would probably make sense to collect examples of cross-library usage at the RDF/JS level, given that reading from a file falls outside the scope of `quadstore` itself. I'll close this one for now and think about it.
